backend:
  name: git-gateway
  branch: tailwind

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "cms"
    label: "Cms"
    folder: "cms"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
